version: '3.9'

services:
  hw2-latex:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hw2-latex-container
    volumes:
      - ./output:/app/output
    command: bash -c "python main.py && tail -f /dev/null"
    stdin_open: true
    tty: true